export const SQL_SCHEMA_TEMPLATE = `-- Setup Database Tables for Lynk.id Membership Pro
-- Run this inside your Supabase SQL Editor

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    sku TEXT UNIQUE NOT NULL,
    price NUMERIC NOT NULL,
    description TEXT,
    download_url TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    license_required BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Members Table
CREATE TABLE IF NOT EXISTS public.members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, EXPIRED, PENDING
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    purchased_products TEXT[] DEFAULT '{}',
    affiliate_code TEXT,
    license_keys JSONB DEFAULT '{}'::jsonb
);

-- 3. Create Webhook Logs Table
CREATE TABLE IF NOT EXISTS public.webhook_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    payload JSONB NOT NULL,
    headers JSONB NOT NULL,
    status TEXT NOT NULL, -- SUCCESS, SIGNATURE_INVALID, PRODUCT_NOT_FOUND, ERROR
    signature_verified BOOLEAN NOT NULL,
    message TEXT
);

-- 4. Create Coupons Table
CREATE TABLE IF NOT EXISTS public.coupons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT NOT NULL, -- PERCENT, FIXED
    discount_value NUMERIC NOT NULL,
    is_active BOOLEAN DEFAULT true,
    used_count INTEGER DEFAULT 0,
    max_uses INTEGER
);

-- 5. Create Affiliates Table
CREATE TABLE IF NOT EXISTS public.affiliates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    commission_rate NUMERIC NOT NULL DEFAULT 10,
    clicks INTEGER DEFAULT 0,
    conversions INTEGER DEFAULT 0,
    total_earnings NUMERIC DEFAULT 0
);

-- 6. Create Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    action TEXT NOT NULL,
    category TEXT NOT NULL, -- MEMBERSHIP, PRODUCT, WEBHOOK, AUTHENTICATION, AUTOMATION, BUSINESS
    details TEXT,
    actor TEXT NOT NULL DEFAULT 'SYSTEM'
);

-- 7. Create License Keys Table
CREATE TABLE IF NOT EXISTS public.license_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key TEXT UNIQUE NOT NULL,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
    member_email TEXT NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' -- ACTIVE, REVOKED
);

-- Enable Row Level Security (RLS) for public access protection
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.license_keys ENABLE ROW LEVEL SECURITY;

-- Create Policies (Admin full access, Members read-only for their own data)
-- For demonstration simplicity, standard supabase service role has full access.
`;

export const NEXT_WEBHOOK_TEMPLATE = `// app/api/webhook/lynk/route.ts
// Next.js 15 Route Handler for Lynk.id Webhook with Secure Signature Validation
import { NextResponse } from "next/server";
import crypto from "crypto";
import { createClient } from "@supabase/supabase-js";

// Initialize Supabase Client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!; // Must use service role to bypass RLS
const supabase = createClient(supabaseUrl, supabaseServiceKey);

const WEBHOOK_SECRET = process.env.LYNK_WEBHOOK_SECRET!;

export async function POST(req: Request) {
  try {
    const rawBody = await req.text();
    const signature = req.headers.get("x-lynk-signature") || "";

    // 1. Validate Lynk.id Webhook Signature
    // Signature is generated by hashing the raw JSON string with your secret key using SHA256 HMAC
    const expectedSignature = crypto
      .createHmac("sha256", WEBHOOK_SECRET)
      .update(rawBody)
      .digest("hex");

    const isSignatureValid = crypto.timingSafeEqual(
      Buffer.from(signature, "utf-8"),
      Buffer.from(expectedSignature, "utf-8")
    );

    if (!isSignatureValid) {
      // Log failed attempt to database
      await supabase.from("webhook_logs").insert({
        payload: JSON.parse(rawBody),
        headers: { "x-lynk-signature": signature },
        status: "SIGNATURE_INVALID",
        signature_verified: false,
        message: "Invalid webhook signature provided by client",
      });

      return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
    }

    const payload = JSON.parse(rawBody);
    const { 
      event,             // e.g., "payment.success"
      transaction_id,    // Unique ID from Lynk.id
      product_sku,       // SKU matches our Product Table
      customer_email,    // Purchaser Email
      customer_name,     // Purchaser Name
      customer_phone,    // Purchaser Phone
      amount,            // Paid amount
      affiliate_code     // Optional affiliate tracking
    } = payload;

    // Check if event is payment success
    if (event !== "payment.success") {
      return NextResponse.json({ message: "Event ignored" }, { status: 200 });
    }

    // 2. Lookup Product by SKU
    const { data: product, error: prodError } = await supabase
      .from("products")
      .select("*")
      .eq("sku", product_sku)
      .single();

    if (prodError || !product) {
      await supabase.from("webhook_logs").insert({
        payload,
        headers: { "x-lynk-signature": signature },
        status: "PRODUCT_NOT_FOUND",
        signature_verified: true,
        message: \`Product with SKU \${product_sku} was not found inside the local database.\`,
      });

      return NextResponse.json({ error: "Product not found" }, { status: 404 });
    }

    // 3. Process Member Registration / Update
    // Upsert Member
    const { data: existingMember } = await supabase
      .from("members")
      .select("*")
      .eq("email", customer_email)
      .single();

    let updatedProducts = [product.id];
    let licenseKeys = {};

    if (existingMember) {
      // If already has access, avoid duplicating
      updatedProducts = Array.from(new Set([...existingMember.purchased_products, product.id]));
      licenseKeys = existingMember.license_keys || {};
    }

    // Generate License key if required
    if (product.license_required && !licenseKeys[product.id]) {
      const generatedKey = \`LNK-PRO-\${crypto.randomBytes(4).toString("hex").toUpperCase()}-\${crypto.randomBytes(4).toString("hex").toUpperCase()}\`;
      licenseKeys[product.id] = generatedKey;

      // Save into license_keys table
      await supabase.from("license_keys").insert({
        key: generatedKey,
        product_id: product.id,
        member_email: customer_email,
        expires_at: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(), // 1 year validity
        status: "ACTIVE"
      });
    }

    const { error: memberError } = await supabase
      .from("members")
      .upsert({
        name: customer_name,
        email: customer_email,
        phone: customer_phone,
        status: "ACTIVE",
        purchased_products: updatedProducts,
        license_keys: licenseKeys,
        affiliate_code: affiliate_code || null
      }, { onConflict: "email" });

    if (memberError) {
      throw memberError;
    }

    // 4. Handle Affiliate Commission
    if (affiliate_code) {
      const { data: affiliate } = await supabase
        .from("affiliates")
        .select("*")
        .eq("code", affiliate_code)
        .single();

      if (affiliate) {
        const commission = (amount * affiliate.commission_rate) / 100;
        await supabase
          .from("affiliates")
          .update({
            conversions: affiliate.conversions + 1,
            total_earnings: Number(affiliate.total_earnings) + commission
          })
          .eq("id", affiliate.id);

        // Audit Log for affiliate
        await supabase.from("audit_logs").insert({
          action: "AFFILIATE_COMMISSION_GRANTED",
          category: "BUSINESS",
          details: \`Granted \${commission} IDR to affiliate \${affiliate.code} for sale to \${customer_email}\`,
          actor: "SYSTEM"
        });
      }
    }

    // 5. Trigger Automations (WhatsApp & Email APIs)
    await triggerAutomations(customer_name, customer_email, customer_phone, product.name, licenseKeys[product.id]);

    // 6. Log Webhook Success
    await supabase.from("webhook_logs").insert({
      payload,
      headers: { "x-lynk-signature": signature },
      status: "SUCCESS",
      signature_verified: true,
      message: \`Successfully provisioned membership for \${customer_email} and unlocked product "\${product.name}".\`,
    });

    // Write Audit Log
    await supabase.from("audit_logs").insert({
      action: "MEMBERSHIP_ACTIVATED",
      category: "MEMBERSHIP",
      details: \`Successfully added product \${product.name} (SKU: \${product_sku}) to \${customer_email}\`,
      actor: "LYNK_WEBHOOK"
    });

    return NextResponse.json({ success: true, message: "Membership activated successfully" });

  } catch (error: any) {
    console.error("Webhook processing failed:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// Simulated automated senders (Email and WhatsApp integrations)
async function triggerAutomations(name: string, email: string, phone: string, productName: string, licenseKey?: string) {
  // Integrate with your preferred provider (e.g., Resend / Mailgun / Fonnte / Wablas)
  const emailBody = \`Halo \${name}, Pembayaran Anda telah kami terima! Akses untuk "\${productName}" telah aktif. \${licenseKey ? "License Key Anda: " + licenseKey : ""}\`;
  
  try {
    // 1. Email Send
    if (process.env.RESEND_API_KEY) {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": \`Bearer \${process.env.RESEND_API_KEY}\`,
        },
        body: JSON.stringify({
          from: "Membership Pro <no-reply@membership-pro.com>",
          to: [email],
          subject: \`Aktivasi Keanggotaan: \${productName}\`,
          html: \`<p>\${emailBody}</p>\`,
        }),
      });
    }

    // 2. WhatsApp Send (e.g. Fonnte Gateway)
    if (phone && process.env.FONNTE_TOKEN) {
      await fetch("https://api.fonnte.com/send", {
        method: "POST",
        headers: {
          "Authorization": process.env.FONNTE_TOKEN,
        },
        body: new URLSearchParams({
          target: phone,
          message: emailBody,
        }),
      });
    }
  } catch (err) {
    console.warn("Automation trigger failed but membership was saved.", err);
  }
}
`;

export const PRISMA_SCHEMA_TEMPLATE = `// prisma/schema.prisma
// Prisma Schema mirror of the Membership Pro architecture

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Product {
  id              String        @id @default(uuid())
  name            String
  sku             String        @unique
  price           Float
  description     String?
  downloadUrl     String        @map("download_url")
  isActive        Boolean       @default(true) @map("is_active")
  licenseRequired Boolean       @default(false) @map("license_required")
  createdAt       DateTime      @default(now()) @map("created_at")
  licenses        LicenseKey[]

  @@map("products")
}

model Member {
  id                String      @id @default(uuid())
  name              String
  email             String      @unique
  phone             String?
  status            String      @default("ACTIVE") // ACTIVE, EXPIRED, PENDING
  joinedAt          DateTime    @default(now()) @map("joined_at")
  purchasedProducts String[]    @map("purchased_products")
  affiliateCode     String?     @map("affiliate_code")
  licenseKeys       Json        @default("{}") @map("license_keys")

  @@map("members")
}

model WebhookLog {
  id                String      @id @default(uuid())
  timestamp         DateTime    @default(now())
  payload           Json
  headers           Json
  status            String      // SUCCESS, SIGNATURE_INVALID, PRODUCT_NOT_FOUND, ERROR
  signatureVerified Boolean     @map("signature_verified")
  message           String?

  @@map("webhook_logs")
}

model Coupon {
  id            String    @id @default(uuid())
  code          String    @unique
  discountType  String    @map("discount_type") // PERCENT, FIXED
  discountValue Float     @map("discount_value")
  isActive      Boolean   @default(true) @map("is_active")
  usedCount     Int       @default(0) @map("used_count")
  maxUses       Int?      @map("max_uses")

  @@map("coupons")
}

model Affiliate {
  id             String   @id @default(uuid())
  code           String   @unique
  name           String
  commissionRate Float    @default(10) @map("commission_rate")
  clicks         Int      @default(0)
  conversions    Int      @default(0)
  totalEarnings  Float    @default(0) @map("total_earnings")

  @@map("affiliates")
}

model AuditLog {
  id        String   @id @default(uuid())
  timestamp DateTime @default(now())
  action    String
  category  String   // MEMBERSHIP, PRODUCT, WEBHOOK, AUTHENTICATION, AUTOMATION, BUSINESS
  details   String?
  actor     String   @default("SYSTEM")

  @@map("audit_logs")
}

model LicenseKey {
  id          String   @id @default(uuid())
  key         String   @unique
  productId   String   @map("product_id")
  product     Product  @relation(fields: [productId], references: [id], onDelete: Cascade)
  memberEmail String   @map("member_email")
  issuedAt    DateTime @default(now()) @map("issued_at")
  expiresAt   DateTime @map("expires_at")
  status      String   @default("ACTIVE") // ACTIVE, REVOKED

  @@map("license_keys")
}
`;

export const README_INSTRUCTIONS = `# LYNK MEMBERSHIP PRO - STARTER KIT DOKUMENTASI

Selamat datang di Starter Kit Lynk Membership Pro! Ini adalah sistem manajemen keanggotaan terintegrasi otomatisasi dengan Webhook Lynk.id, menggunakan stack modern **Next.js 15, Tailwind CSS, Prisma, dan Supabase**.

## Cara Setup & Konfigurasi di Vercel + Supabase

### Langkah 1: Persiapan Database Supabase
1. Masuk ke dashboard [Supabase](https://supabase.com).
2. Buat project baru dan pilih Region terdekat (misal: Singapore).
3. Salin SQL dari tab **Supabase SQL Schema** di dashboard ini, lalu tempelkan ke SQL Editor di Supabase, kemudian jalankan (**Run**).

### Langkah 2: Buat Project Next.js & Hubungkan Prisma
1. Buat folder proyek Anda, salin file Prisma schema (\`prisma/schema.prisma\`) dan Next.js Webhook Router (\`app/api/webhook/lynk/route.ts\`).
2. Instal dependensi yang diperlukan:
   \`\`\`bash
   npm install @prisma/client @supabase/supabase-js
   npm install -D prisma
   \`\`\`
3. Jalankan migrasi atau generate Prisma Client:
   \`\`\`bash
   npx prisma db pull --force
   npx prisma generate
   \`\`\`

### Langkah 3: Setup Environment Variables di Vercel
Tambahkan variabel berikut pada project Vercel Anda di menu **Settings → Environment Variables**:

| Variable Name | Description | Example / Source |
|---|---|---|
| \`DATABASE_URL\` | PostgreSQL connection string dari Supabase | \`postgresql://postgres:[password]@...\` |
| \`NEXT_PUBLIC_SUPABASE_URL\` | URL API Supabase Anda | \`https://[project-id].supabase.co\` |
| \`SUPABASE_SERVICE_ROLE_KEY\`| Service key Supabase untuk memintas RLS | Dapat ditemukan di Supabase API Settings |
| \`LYNK_WEBHOOK_SECRET\` | Kunci Secret Webhook dari Lynk.id | Dapat disalin dari dashboard Admin Lynk.id |
| \`RESEND_API_KEY\` | Opsional. Token API kirim email otomatis | Dari dashboard Resend.com |
| \`FONNTE_TOKEN\` | Opsional. Token API kirim WhatsApp otomatis | Dari dashboard Fonnte.com |

### Langkah 4: Menghubungkan Webhook ke Lynk.id
1. Deploy Next.js project Anda ke Vercel. Anda akan mendapatkan URL publik, contoh: \`https://lynk-membership.vercel.app\`.
2. URL webhook Anda adalah: \`https://lynk-membership.vercel.app/api/webhook/lynk\`.
3. Masuk ke Akun Admin **Lynk.id** Anda.
4. Pergi ke menu **Webhook Settings / Integrasi Developer**.
5. Masukkan URL Webhook di atas.
6. Masukkan **Webhook Secret Key** yang telah Anda tetapkan di Environment Variables.
7. Simpan perubahan. Kini setiap pembayaran sukses di Lynk.id akan otomatis mengaktivasi member di website Anda secara real-time!
`;
